apiVersion: infinispan.org/v1
kind: Infinispan
metadata:
  name: datagrid
spec:
  image: quay.io/infinispan/server:12.1.0.Final
  container:
    cpu: "1000m"
    memory: 4Gi
  expose:
    type: LoadBalancer
  replicas: 2
  security:
    endpointEncryption:
      type: None
    endpointAuthentication: false
  service:
    type: DataGrid
    sites:
      local:
        name: SITE_NAME
        expose:
          type: LoadBalancer
      locations:
        - name: AWS
          url: openshift://api.summit-aws.28ts.p1.openshiftapps.com:6443
          secretName: aws-token
        - name: GCP
          url: openshift://api.summit-gcp.eior.p2.openshiftapps.com:6443
          secretName: gcp-token
        - name: AZURE
          url: openshift://api.g9dkpkud.centralus.aroapp.io:6443
          secretName: azure-token
  logging:
    categories:
      org.jgroups.protocols.TCP: error
      org.jgroups.protocols.relay.RELAY2: error