kubectl delete validatingwebhookconfigurations.admissionregistration.k8s.io/validation.webhook.eventing.knative.dev
kubectl delete validatingwebhookconfigurations.admissionregistration.k8s.io/validation.webhook.serving.knative.dev
