---
apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaTopic
metadata:
  name: match-updates
  labels:
    strimzi.io/cluster: demo2021
spec:
  partitions: 50
  replicas: 3
  config:
    retention.ms: -1
    segment.bytes: 1073741824

---
apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaTopic
metadata:
  name: player-matches-intermediary
  labels:
    strimzi.io/cluster: demo2021
spec:
  partitions: 50
  replicas: 3
  config:
    retention.ms: -1
    segment.bytes: 1073741824

---
apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaTopic
metadata:
  name: player-matches-aggregated
  labels:
    strimzi.io/cluster: demo2021
spec:
  partitions: 50
  replicas: 3
  config:
    retention.ms: -1
    segment.bytes: 1073741824

---
apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaTopic
metadata:
  name: matches-aggregated
  labels:
    strimzi.io/cluster: demo2021
spec:
  partitions: 50
  replicas: 3
  config:
    retention.ms: -1
    segment.bytes: 1073741824